on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
